name: Firmware Build

permissions:
  actions: write  
  contents: read  

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-arm-none-eabi cmake ninja-build jq

    - name: Configure (CMake + Ninja)
      run: |
        mkdir -p build/Release
        cd build/Release
        cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release ../..

    - name: Build
      run: |
        cd build/Release
        ninja

    - name: Delete all previous workflow runs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CURRENT_RUN_ID: ${{ github.run_id }}
      run: |
        runs=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github+json" \
          "https://api.github.com/repos/$GITHUB_REPOSITORY/actions/runs" \
          | jq '.workflow_runs[] | select(.id != '"$CURRENT_RUN_ID"') | .id')
        
        for run_id in $runs; do
          curl -X DELETE -H "Authorization: token $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github+json" \
              "https://api.github.com/repos/$GITHUB_REPOSITORY/actions/runs/$run_id"
        done
