name: Build STM32 and Generate Badges

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-arm-none-eabi binutils-arm-none-eabi cmake ninja-build

    - name: Configure (CMake + Ninja)
      run: |
        mkdir -p build/Release
        cd build/Release
        cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release ../..

    - name: Build
      run: |
        cd build/Release
        ninja

